### ISSUE TITLE
Set up Webpack with ReactJS

### ISSUE THREAD

**Issue by pllearns** [GuildCrafts/lizardboard#17]
-As an alternate homepage
-As a user I should be able to utilize the dashboard and interact with nav menu items

**Comment by jamestewartjr** [comment]
It seems webpack is a dependency. Is there more to this issue @jrob8577?

**Comment by jrobcodes** [comment]
Nope, didn't think this was a thing.  I think eventually I could see an issue being created to figure out webpack to combine both front and back end projects, but I'll close this one.
