### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by jrobcodes** [GuildCrafts/lizardboard#3]
As a developer, I want a CONTRIBUTING.md, so that I may understand expectations for contributing to the lizardboard project.

**Comment by Moniarchy** [comment]
@shakalee14 and I have added a CONTRIBUTING.md (and a README.md) in our branch (https://github.com/GuildCrafts/lizardboard/pull/12)

**Comment by jrobcodes** [comment]
Closed by #8
